config/routes.rb
Ecn::Application.routes.draw do


  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  #authenticated :user do
    #root :to => 'home#index'
  #end

  devise_for :users
  resources :users, :only => [:show, :index]
  match '/recent'=>"home#recent",:as=>:recent
  match '/popular'=>"home#popular",:as=>:popular
  match '/search'=>"home#search",:as=>:search
  match '/archive/:day'=>"home#day",:as=>:day
  match '/archive'=>"home#archive",:as=>:archive
  match '/test'=>"home#test",:as=>:test
  match '/p-:product_url'=>"home#product",:as=>:product
  match '/c-:company_url'=>"home#company",:as=>:company

  resque_constraint = lambda do |request|
    Rails.env.development? or 
      (request.env['warden'].authenticate? and request.env['warden'].user.has_role?(:admin))
  end
  constraints resque_constraint do
    mount Resque::Server.new, :at => "/resque"
  end
  match '/:topic_name/update_count'=>"home#update_count",:as=>:update_count,:via=>:post
  match '/status'=>"home#status",:as=>:status
  match '/:topic_name'=>"home#topic",:as=>:topic
  root :to => "home#index"
end

app/helpers/layout_helper.rb
# -*- encoding : utf-8 -*-
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, page_header = nil, show_title = true)
    page_header ||= page_title
    if params[:page].present? and params[:page].to_i > 1
      page_title = "Page #{params[:page]}_#{page_title}" 
      page_header += " / Page #{params[:page]}"
    end
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
    if show_title
      content_for(:header) { h(page_header.to_s) }      
    end
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
  def meta(name,content)
    content_for(:head){
      "<meta name='#{name}' content='#{content}' />".html_safe
    }
  end
  def metalink rel,href
    content_for(:head){
      "<link rel='#{rel}' href='#{href}' />".html_safe
    }
  end
  def meta_noindex
    meta('robots','noindex')
  end
  def is_home?
    request.url == root_url
  end
  def text_link_to text,url,options={}
    # "<tt class='text_link' longdesc='#{url}'>#{text}</tt>".html_safe
    
  end
  def js_external_link_to url
    "<script type='text/javascript'>
      document.write(\"<a href='#{url}' target='_blank' rel='nofollow'><img src='/assets/go.gif' /></a>\")
    </script>".html_safe
  end
  def js_write text
    "<script type='text/javascript'>
      document.write('#{text}')
    </script>".html_safe
  end
  
  def pint i
    i.to_i > 1 ? " - 第#{i}页" : nil
  end
  
  def next_page
    params[:page].to_i+1
  end
  def prev_page
    params[:page].to_i == 2 ? nil : params[:page].to_i-1
  end
  def kami_array num
    num = 400 if num > 400
    Kaminari::PaginatableArray.new([],:limit=>40,:offset=>40*(params[:page].to_i - 1),:total_count=>num)
  end
  
    def nofollow_sub str
    str.gsub(/<(a href="[^"]+?")>/,'<\1 rel="">').gsub(/rel\=\"/,"rel=\"nofollow ").html_safe
  end
  def jsemail(str)
    ('<SCRIPT TYPE="text/javascript">
emailE=("'+str.reverse+'").split("").reverse().join("");
document.write(\'<A href="mailto:\' + emailE + \'">\' + emailE + \'</a>\')
 //-->
</script>

<NOSCRIPT>
    <em>Email address protected by JavaScript.<BR>
    Please enable JavaScript to contact me.</em>
</NOSCRIPT>').html_safe
  end
  def js_link_to str,href
    "<a href='javascript://' onclick=goto('#{href.to_rev}',this)>#{str}</a>".html_safe
    # "<a href='javascript://' class='rl' data='#{href.to_rev}'>#{str}</a>".html_safe
  end
end

app/views/layouts/_col1.haml
-if show_title?
  .page-header
    %h1=yield :header
= yield

app/views/layouts/_col2l.haml
.span2#primary
  =render 'layouts/primary'
.span10#content
  -if show_title?
    %h1=yield :header
  = yield

app/views/layouts/_col2r.haml
.row
  .span9#content
    -if show_title?
      %h1=yield :header
    = yield
  .span3.sidebar#secondary
    =render 'layouts/secondary'

app/views/layouts/_col3.haml
.span2#primary
  =render 'layouts/primary'
.span7#content
  -if show_title?
    %h1=yield :header
  = yield
.span3#secondary
  =render 'layouts/secondary'

app/views/layouts/_iefix.erb
<!--[if lt IE 9]>
<%= javascript_include_tag "html5shiv"%>
<![endif]-->
<!--[if IE 6]>    
	<%= stylesheet_link_tag "ie6"%>
<![endif]-->

app/views/layouts/_iefixjs.erb
<!--[if IE 6]>    
	<%= javascript_include_tag    "ie6"%>
<![endif]-->

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to @current_app.name, root_url, :class => 'brand',:rel=>"nofollow"
%form.navbar-search.pull-left{:action=>'/search',:method=>'get'}
  -a={:id=>'q',:type=>"text",:name=>"q"}
  -a.merge! @q.nil?  ? {:placeholder=>'Search'} : {:value=>@q}
  %input.search-query{a}
%ul.nav
  %li=link_to 'Archives','/archive'
  %li=link_to 'Recent','/recent'
  %li=link_to 'Popular','/popular'
= render :partial => 'users/nav' if Rails.env.development?

app/views/layouts/_secondary.haml
=yield :sidebar

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : @current_app.name
    = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags
    = yield(:head)
    =render "layouts/iefix"
  %body{:class=>(@body_class || [controller_name,action_name].join('-'))}
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          =render 'layouts/messages'
          =render "layouts/#{@cols || 'col1'}"
    %footer
      .container
        -cache "belts-#{@current_app.name}",:expires_in => 1.minutes do
          -pages = (@current_app.topics.present.count / 100).ceil
          -i=1
          .index
            -while i <= pages do
              =link_to i,recent_url(:page=>i)
              -i+=10
        &copy; 2012

    = javascript_include_tag "application"
    =render "layouts/iefixjs"
    .hidden
      =javascript_include_tag 'http://s21.cnzz.com/stat.php?id=2966530&web_id=2966530'
    = yield(:footer)